version: '3.8'

services:
  # Servidor de Aplicaciones Apache
  web_papeleria:
    image: httpd:latest
    container_name: apache_servidor
    ports:
      - "8080:80"

  # Gestor de Base de Datos MySQL
  db_papeleria:
    image: mysql:8.0
    container_name: mysql_servidor
    environment:
      MYSQL_ROOT_PASSWORD: 1193039777Jerson/
      MYSQL_DATABASE: papeleria_online_db
    ports:
      - "3306:3306"